---
- name: install jdk / Debian
  become: yes
  apt:
    name: "openjdk-{{ jdk_version }}-jdk-headless"
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: install jdk / Red Hat
  become: yes
  yum:
    name: "java-{{ jdk_version }}-openjdk-devel"
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat"
